name: home-navigation

services:
  web:
    build: .
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - ./migrations:/app/migrations
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=sqlite:////app/instance/links.db
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "mkdir -p /app/instance &&
             touch /app/instance/links.db &&
             chmod 666 /app/instance/links.db &&
             flask db init &&
             flask db migrate -m 'Initial migration' &&
             flask db upgrade &&
             flask create-admin &&
             gunicorn --bind 0.0.0.0:5000 app:app" 