name: home-navigation

services:
  web:
    build: .
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - ./links.db:/app/links.db
      - ./migrations:/app/migrations
    environment:
      - FLASK_APP=app.py
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "flask db upgrade &&
             flask create-admin &&
             gunicorn --bind 0.0.0.0:5000 app:app" 