name: home-navigation

services:
  web:
    build: .
    user: "1001:1001"
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - ./migrations:/app/migrations
      - ./instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=sqlite:////app/instance/links.db
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "gunicorn --bind 0.0.0.0:5000 app:app" 