name: home-navigation

services:
  web:
    build: .
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - ./migrations:/app/migrations
      - ./instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=sqlite:////app/instance/links.db
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "mkdir -p /app/instance &&
             mkdir -p /app/migrations/versions &&
             touch /app/instance/links.db &&
             chmod -R 777 /app/instance &&
             chmod -R 777 /app/migrations &&
             flask db init || true &&
             flask db migrate -m 'Initial migration' || true &&
             flask db upgrade &&
             flask create-admin || true &&
             gunicorn --bind 0.0.0.0:5000 app:app" 