"""添加用户锁定和IP限制功能

Revision ID: 49fd44a5afe9
Revises: 4133e604cdf7
Create Date: 2025-02-02 17:55:17.709108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49fd44a5afe9'
down_revision = '4133e604cdf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_failed_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_failed_login')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('is_locked')

    # ### end Alembic commands ###
