"""同步模型

Revision ID: 4c299d480f86
Revises: b49f4831f580
Create Date: 2025-02-06 12:44:44.330167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c299d480f86'
down_revision = 'b49f4831f580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_category_region_id', 'regions', ['region_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_category_region_id', type_='foreignkey')
        batch_op.drop_column('region_id')

    # ### end Alembic commands ###
